export const categories = [
    { "id": 1, "name": "Information Technology & Software"},
    { "id": 2, "name": "Engineering & Technical Fields"},
    { "id": 3, "name": "Accounting, Finance & Banking"},
    { "id": 4, "name": "Business & Management"},
    { "id": 5, "name": "Marketing, Sales & Retail" },
    { "id": 6, "name": "Healthcare & Pharmaceuticals"},
    { "id": 7, "name": "Education & Training" },
    { "id": 8, "name": "Human Resources & Recruitment"},
    { "id": 9, "name": "Logistics, Supply Chain & Procurement" },
    { "id": 10, "name": "Legal Services"},
    { "id": 11, "name": "Admin & Clerical"},
    { "id": 12, "name": "Customer Service & Support"},
    { "id": 13, "name": "FMCG & Manufacturing"},
    { "id": 14, "name": "Agriculture & Natural Resources"},
    { "id": 15, "name": "Architecture & Construction"},
    { "id": 16, "name": "Automotive & Transportation" },
    { "id": 17, "name": "Creative Arts & Design"},
    { "id": 18, "name": "Environment, Water & Sanitation"},
    { "id": 19, "name": "Consulting & Strategy"},
    { "id": 20, "name": "Economics & Research"},
    { "id": 21, "name": "Development & Project Management",},
    { "id": 22, "name": "Communications, Media & Journalism" },
    { "id": 23, "name": "Retail, Wholesale & Distribution" },
    { "id": 24, "name": "Security & Law Enforcement"},
    { "id": 25, "name": "Event, Travel & Tourism" },
    { "id": 26, "name": "Natural & Social Sciences" },
    { "id": 27, "name": "Telecommunications & Networking"},
    { "id": 28, "name": "Hospitality & Hotel Services" },
    { "id": 29, "name": "Veterinary & Animal Services" },
    { "id": 30, "name": "Quality Assurance & Safety"}
  ];